# Generated by Django 5.2 on 2025-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_customfield_funcionario_delete_customfieldconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Department',
            new_name='Departamento',
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
    ]
