# Generated by Django 5.2 on 2025-05-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_campopersonalizado_rename_department_departamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='max_employees',
            new_name='funcionarios',
        ),
    ]
